syntax = "proto3";

package federated;

option go_package = "github.com/lukam/actor-framework/federated/protogen;federatedpb";


message RegisterTrainer {
  string trainer_id = 1;
  int32 dataset_size = 2;
  string address = 3;
}

message StartRound {
  int32 round_number = 1;
  bytes global_weights = 2;
  string aggregator_address = 3;
}

message LocalUpdate {
  string trainer_id = 1;
  int32 round_number = 2;
  bytes updated_weights = 3;
  int32 dataset_size = 4;
  double local_loss = 5;
}

message AggregationComplete {
  int32 round_number = 1;
  bytes new_global_weights = 2;
}

message EvaluateModel {
  int32 round_number = 1;
  bytes weights = 2;
  string test_data_path = 3;
}

message F1Score {
  double precision = 1;
  double recall = 2;
  double f1 = 3;
}

message EvaluationResult {
  int32 round_number = 1;
  double accuracy = 2;
  map<string, F1Score> class_metrics = 3;
  repeated int32 confusion_matrix = 4;
}

message TrainingComplete {
  int32 total_rounds = 1;
  double final_accuracy = 2;
  int64 duration = 3;
}

message LogEntry {
  int64 timestamp_unix_ms = 1;
  string source_actor = 2;
  string level = 3;
  string message = 4;
}

message PeerSync {
  string peer_id = 1;
  int32 round_number = 2;
  bytes local_weights = 3;
  int32 dataset_size = 4;
  bytes crdt_state = 5;
}
