// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: federated.proto

package federatedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTrainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainerId     string                 `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	DatasetSize   int32                  `protobuf:"varint,2,opt,name=dataset_size,json=datasetSize,proto3" json:"dataset_size,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTrainer) Reset() {
	*x = RegisterTrainer{}
	mi := &file_federated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrainer) ProtoMessage() {}

func (x *RegisterTrainer) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrainer.ProtoReflect.Descriptor instead.
func (*RegisterTrainer) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTrainer) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *RegisterTrainer) GetDatasetSize() int32 {
	if x != nil {
		return x.DatasetSize
	}
	return 0
}

func (x *RegisterTrainer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type StartRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber       int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	GlobalWeights     []byte                 `protobuf:"bytes,2,opt,name=global_weights,json=globalWeights,proto3" json:"global_weights,omitempty"`
	AggregatorAddress string                 `protobuf:"bytes,3,opt,name=aggregator_address,json=aggregatorAddress,proto3" json:"aggregator_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartRound) Reset() {
	*x = StartRound{}
	mi := &file_federated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRound) ProtoMessage() {}

func (x *StartRound) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRound.ProtoReflect.Descriptor instead.
func (*StartRound) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{1}
}

func (x *StartRound) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *StartRound) GetGlobalWeights() []byte {
	if x != nil {
		return x.GlobalWeights
	}
	return nil
}

func (x *StartRound) GetAggregatorAddress() string {
	if x != nil {
		return x.AggregatorAddress
	}
	return ""
}

type LocalUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrainerId      string                 `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	RoundNumber    int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	UpdatedWeights []byte                 `protobuf:"bytes,3,opt,name=updated_weights,json=updatedWeights,proto3" json:"updated_weights,omitempty"`
	DatasetSize    int32                  `protobuf:"varint,4,opt,name=dataset_size,json=datasetSize,proto3" json:"dataset_size,omitempty"`
	LocalLoss      float64                `protobuf:"fixed64,5,opt,name=local_loss,json=localLoss,proto3" json:"local_loss,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalUpdate) Reset() {
	*x = LocalUpdate{}
	mi := &file_federated_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUpdate) ProtoMessage() {}

func (x *LocalUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUpdate.ProtoReflect.Descriptor instead.
func (*LocalUpdate) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{2}
}

func (x *LocalUpdate) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *LocalUpdate) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *LocalUpdate) GetUpdatedWeights() []byte {
	if x != nil {
		return x.UpdatedWeights
	}
	return nil
}

func (x *LocalUpdate) GetDatasetSize() int32 {
	if x != nil {
		return x.DatasetSize
	}
	return 0
}

func (x *LocalUpdate) GetLocalLoss() float64 {
	if x != nil {
		return x.LocalLoss
	}
	return 0
}

type AggregationComplete struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber      int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	NewGlobalWeights []byte                 `protobuf:"bytes,2,opt,name=new_global_weights,json=newGlobalWeights,proto3" json:"new_global_weights,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregationComplete) Reset() {
	*x = AggregationComplete{}
	mi := &file_federated_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationComplete) ProtoMessage() {}

func (x *AggregationComplete) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationComplete.ProtoReflect.Descriptor instead.
func (*AggregationComplete) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{3}
}

func (x *AggregationComplete) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *AggregationComplete) GetNewGlobalWeights() []byte {
	if x != nil {
		return x.NewGlobalWeights
	}
	return nil
}

type EvaluateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Weights       []byte                 `protobuf:"bytes,2,opt,name=weights,proto3" json:"weights,omitempty"`
	TestDataPath  string                 `protobuf:"bytes,3,opt,name=test_data_path,json=testDataPath,proto3" json:"test_data_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateModel) Reset() {
	*x = EvaluateModel{}
	mi := &file_federated_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateModel) ProtoMessage() {}

func (x *EvaluateModel) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateModel.ProtoReflect.Descriptor instead.
func (*EvaluateModel) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateModel) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *EvaluateModel) GetWeights() []byte {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *EvaluateModel) GetTestDataPath() string {
	if x != nil {
		return x.TestDataPath
	}
	return ""
}

type F1Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precision     float64                `protobuf:"fixed64,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Recall        float64                `protobuf:"fixed64,2,opt,name=recall,proto3" json:"recall,omitempty"`
	F1            float64                `protobuf:"fixed64,3,opt,name=f1,proto3" json:"f1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F1Score) Reset() {
	*x = F1Score{}
	mi := &file_federated_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F1Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F1Score) ProtoMessage() {}

func (x *F1Score) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F1Score.ProtoReflect.Descriptor instead.
func (*F1Score) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{5}
}

func (x *F1Score) GetPrecision() float64 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *F1Score) GetRecall() float64 {
	if x != nil {
		return x.Recall
	}
	return 0
}

func (x *F1Score) GetF1() float64 {
	if x != nil {
		return x.F1
	}
	return 0
}

type EvaluationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber     int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Accuracy        float64                `protobuf:"fixed64,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	ClassMetrics    map[string]*F1Score    `protobuf:"bytes,3,rep,name=class_metrics,json=classMetrics,proto3" json:"class_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfusionMatrix []int32                `protobuf:"varint,4,rep,packed,name=confusion_matrix,json=confusionMatrix,proto3" json:"confusion_matrix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvaluationResult) Reset() {
	*x = EvaluationResult{}
	mi := &file_federated_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResult) ProtoMessage() {}

func (x *EvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResult.ProtoReflect.Descriptor instead.
func (*EvaluationResult) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluationResult) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *EvaluationResult) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *EvaluationResult) GetClassMetrics() map[string]*F1Score {
	if x != nil {
		return x.ClassMetrics
	}
	return nil
}

func (x *EvaluationResult) GetConfusionMatrix() []int32 {
	if x != nil {
		return x.ConfusionMatrix
	}
	return nil
}

type TrainingComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRounds   int32                  `protobuf:"varint,1,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	FinalAccuracy float64                `protobuf:"fixed64,2,opt,name=final_accuracy,json=finalAccuracy,proto3" json:"final_accuracy,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingComplete) Reset() {
	*x = TrainingComplete{}
	mi := &file_federated_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingComplete) ProtoMessage() {}

func (x *TrainingComplete) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingComplete.ProtoReflect.Descriptor instead.
func (*TrainingComplete) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{7}
}

func (x *TrainingComplete) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *TrainingComplete) GetFinalAccuracy() float64 {
	if x != nil {
		return x.FinalAccuracy
	}
	return 0
}

func (x *TrainingComplete) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type LogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	SourceActor     string                 `protobuf:"bytes,2,opt,name=source_actor,json=sourceActor,proto3" json:"source_actor,omitempty"`
	Level           string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_federated_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *LogEntry) GetSourceActor() string {
	if x != nil {
		return x.SourceActor
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeerSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	LocalWeights  []byte                 `protobuf:"bytes,3,opt,name=local_weights,json=localWeights,proto3" json:"local_weights,omitempty"`
	DatasetSize   int32                  `protobuf:"varint,4,opt,name=dataset_size,json=datasetSize,proto3" json:"dataset_size,omitempty"`
	CrdtState     []byte                 `protobuf:"bytes,5,opt,name=crdt_state,json=crdtState,proto3" json:"crdt_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSync) Reset() {
	*x = PeerSync{}
	mi := &file_federated_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSync) ProtoMessage() {}

func (x *PeerSync) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSync.ProtoReflect.Descriptor instead.
func (*PeerSync) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{9}
}

func (x *PeerSync) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerSync) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *PeerSync) GetLocalWeights() []byte {
	if x != nil {
		return x.LocalWeights
	}
	return nil
}

func (x *PeerSync) GetDatasetSize() int32 {
	if x != nil {
		return x.DatasetSize
	}
	return 0
}

func (x *PeerSync) GetCrdtState() []byte {
	if x != nil {
		return x.CrdtState
	}
	return nil
}

var File_federated_proto protoreflect.FileDescriptor

const file_federated_proto_rawDesc = "" +
	"\n" +
	"\x0ffederated.proto\x12\tfederated\"m\n" +
	"\x0fRegisterTrainer\x12\x1d\n" +
	"\n" +
	"trainer_id\x18\x01 \x01(\tR\ttrainerId\x12!\n" +
	"\fdataset_size\x18\x02 \x01(\x05R\vdatasetSize\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x85\x01\n" +
	"\n" +
	"StartRound\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12%\n" +
	"\x0eglobal_weights\x18\x02 \x01(\fR\rglobalWeights\x12-\n" +
	"\x12aggregator_address\x18\x03 \x01(\tR\x11aggregatorAddress\"\xba\x01\n" +
	"\vLocalUpdate\x12\x1d\n" +
	"\n" +
	"trainer_id\x18\x01 \x01(\tR\ttrainerId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12'\n" +
	"\x0fupdated_weights\x18\x03 \x01(\fR\x0eupdatedWeights\x12!\n" +
	"\fdataset_size\x18\x04 \x01(\x05R\vdatasetSize\x12\x1d\n" +
	"\n" +
	"local_loss\x18\x05 \x01(\x01R\tlocalLoss\"f\n" +
	"\x13AggregationComplete\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12,\n" +
	"\x12new_global_weights\x18\x02 \x01(\fR\x10newGlobalWeights\"r\n" +
	"\rEvaluateModel\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12\x18\n" +
	"\aweights\x18\x02 \x01(\fR\aweights\x12$\n" +
	"\x0etest_data_path\x18\x03 \x01(\tR\ftestDataPath\"O\n" +
	"\aF1Score\x12\x1c\n" +
	"\tprecision\x18\x01 \x01(\x01R\tprecision\x12\x16\n" +
	"\x06recall\x18\x02 \x01(\x01R\x06recall\x12\x0e\n" +
	"\x02f1\x18\x03 \x01(\x01R\x02f1\"\xa5\x02\n" +
	"\x10EvaluationResult\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x01R\baccuracy\x12R\n" +
	"\rclass_metrics\x18\x03 \x03(\v2-.federated.EvaluationResult.ClassMetricsEntryR\fclassMetrics\x12)\n" +
	"\x10confusion_matrix\x18\x04 \x03(\x05R\x0fconfusionMatrix\x1aS\n" +
	"\x11ClassMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.federated.F1ScoreR\x05value:\x028\x01\"x\n" +
	"\x10TrainingComplete\x12!\n" +
	"\ftotal_rounds\x18\x01 \x01(\x05R\vtotalRounds\x12%\n" +
	"\x0efinal_accuracy\x18\x02 \x01(\x01R\rfinalAccuracy\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\"\x89\x01\n" +
	"\bLogEntry\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12!\n" +
	"\fsource_actor\x18\x02 \x01(\tR\vsourceActor\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xad\x01\n" +
	"\bPeerSync\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12#\n" +
	"\rlocal_weights\x18\x03 \x01(\fR\flocalWeights\x12!\n" +
	"\fdataset_size\x18\x04 \x01(\x05R\vdatasetSize\x12\x1d\n" +
	"\n" +
	"crdt_state\x18\x05 \x01(\fR\tcrdtStateBAZ?github.com/lukam/actor-framework/federated/protogen;federatedpbb\x06proto3"

var (
	file_federated_proto_rawDescOnce sync.Once
	file_federated_proto_rawDescData []byte
)

func file_federated_proto_rawDescGZIP() []byte {
	file_federated_proto_rawDescOnce.Do(func() {
		file_federated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_proto_rawDesc), len(file_federated_proto_rawDesc)))
	})
	return file_federated_proto_rawDescData
}

var file_federated_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_federated_proto_goTypes = []any{
	(*RegisterTrainer)(nil),     // 0: federated.RegisterTrainer
	(*StartRound)(nil),          // 1: federated.StartRound
	(*LocalUpdate)(nil),         // 2: federated.LocalUpdate
	(*AggregationComplete)(nil), // 3: federated.AggregationComplete
	(*EvaluateModel)(nil),       // 4: federated.EvaluateModel
	(*F1Score)(nil),             // 5: federated.F1Score
	(*EvaluationResult)(nil),    // 6: federated.EvaluationResult
	(*TrainingComplete)(nil),    // 7: federated.TrainingComplete
	(*LogEntry)(nil),            // 8: federated.LogEntry
	(*PeerSync)(nil),            // 9: federated.PeerSync
	nil,                         // 10: federated.EvaluationResult.ClassMetricsEntry
}
var file_federated_proto_depIdxs = []int32{
	10, // 0: federated.EvaluationResult.class_metrics:type_name -> federated.EvaluationResult.ClassMetricsEntry
	5,  // 1: federated.EvaluationResult.ClassMetricsEntry.value:type_name -> federated.F1Score
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_federated_proto_init() }
func file_federated_proto_init() {
	if File_federated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_proto_rawDesc), len(file_federated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_federated_proto_goTypes,
		DependencyIndexes: file_federated_proto_depIdxs,
		MessageInfos:      file_federated_proto_msgTypes,
	}.Build()
	File_federated_proto = out.File
	file_federated_proto_goTypes = nil
	file_federated_proto_depIdxs = nil
}
